site_name: QCoro
site_description: QCoro is a C++ framework for using coroutines with Qt
site_author: Daniel Vrátil
copyright: Copyright &copy <a href="https://www.dvratil.cz">Daniel Vrátil</a>, all contents published under <a href="https://www.gnu.org/licenses/fdl-1.3.html">GNU FDL 1.3</a>, unless stated otherwise.
repo_url: https://github.com/dvratil/qcoro
repo_name: 'QCoro on GitHub'
edit_uri: ''

theme:
  name: mkdocs
  highlightjs: true
  hljs_languages:
      - cpp
  nav_style: dark

plugins:
  - awesome-pages

