site_name: QCoro
site_description: QCoro is a C++ framework for using coroutines with Qt
site_author: Daniel Vrátil
copyright: Copyright &copy <a href="https://www.dvratil.cz">Daniel Vrátil</a>, all contents published under <a href="https://www.gnu.org/licenses/fdl-1.3.html">GNU FDL 1.3</a>, unless stated otherwise.
repo_url: https://github.com/danvratil/qcoro
repo_name: 'QCoro on GitHub'
edit_uri: ''

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.expand

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition

plugins:
  - search
  - include-markdown

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/danvratil
    - icon: fontawesome/brands/github
      link: https://github.com/danvratil

nav:
    - Home: index.md
    - Building and Using QCoro: building-and-using.md
    - Coroutines:
        - Qt vs. co_await: coroutines/qt-vs-coawait.md
        - co_await Explained: coroutines/coawait.md
        - Further Reading: coroutines/reading.md
    - Reference:
        - QCoro::Task<T>: reference/task.md
        - QCoro::coro(): reference/coro.md
        - Supported Types:
          - QAbstractSocket: reference/qabstractsocket.md
          - QDBusPendingCall: reference/qdbuspendingcall.md
          - QDBusPendingReply: reference/qdbuspendingreply.md
          - QFuture: reference/qfuture.md
          - QIODevice: reference/qiodevice.md
          - QLocalSocket: reference/qlocalsocket.md
          - QNetworkReply: reference/qnetworkreply.md
          - QProcess: reference/qprocess.md
          - QTimer: reference/qtimer.md
          - QTcpServer: reference/qtcpserver.md
    - About:
        - License: about/license.md
