name: Generate documentation

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install mkdocs mkdocs-awesome-pages-plugin
      - name: Build
        run: |
          mkdocs build -d /tmp/site
      - name: Commit files
        run: |
          git checkout gh-pages
          cp /tmp/site* ./
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Update docs from main branch ${{ github.sha }}" -a          
      - name: Publish
        if: success()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
