name: Generate documentation

on:
  push:
    branches:
      - main
    paths:
      - 'mkdocs.yml'
      - 'docs/**'

  workflow_dispatch:

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
      - name: Build
        run: |
          echo "{% extends \"base.html\" %}{% block analytics %}<!-- Matomo -->
            <script type=\"text/javascript\">
              var _paq = window._paq = window._paq || [];
              _paq.push(['disableCookies']);
              _paq.push(['trackPageView']);
              _paq.push(['enableLinkTracking']);
              (function() { var u='//analytics.dvratil.cz/';
                _paq.push(['setTrackerUrl', u+'matomo.php']);
                _paq.push(['setSiteId', '2']);
                var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
                g.type='text/javascript'; g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
              })();</script><!-- End Matomo Code -->{% endblock %}" > docs/overrides/main.html
          mkdocs build -d /tmp/site
      - name: Commit files
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git rm -r assets
          cp -r /tmp/site/* ./
          git add -A
          git commit -m "Update docs from main branch ${{ github.sha }}" -a
      - name: Publish
        if: success()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
